module2-task2
htmlacademy-nodejs/257463-kekstagram pull request #5
Opened 2018-10-02 09:02 UTC by AndrewBalak

2018-10-02 17:59 UTC, Donnyyyyy requested changes

2018-10-02 17:59 UTC, Donnyyyyy commented on Web.config
> +﻿<?xml version="1.0"?>
а зачем нужен этот конфиг?

2018-10-03 07:24 UTC, AndrewBalak commented on Web.config
> +﻿<?xml version="1.0"?>
Visual studio сгенерировала(для ASP.net), для node.js оно не нужно, добавил в gitignore

2018-10-03 07:25 UTC, AndrewBalak commented on Web.config
> +﻿<?xml version="1.0"?>
Из репозитория можно удалить

2018-10-03 07:48 UTC, Donnyyyyy approved these changes

2018-10-03 07:48 UTC, merged